<section>
    <ul>
                <li>
                    <dl>
                        <dt>
                            名前：{{$user->name}}
                        </dt>
                        <dt>
                            年齢：{{$user->age}}歳</p>
                        </dt>
                        <dt>
                            性別:{{$user->gender}}
                        </dt>
                        <dt>
                            現在のバイト:{{$user->current_job}}
                        </dt>
                        <dt>
                            メールアドレス:{{$user->email}}
                        </dt>
                        </dd>
                    </dl>
                </li>
</section>
